name: mininet-vm-build

on: [push, pull_request]

jobs:
  build:
    name: Mininet VM Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flavor: [focal64server, bionic64server, xenial64server, xenial32server]
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.x
      - name: Install VM build dependencies
        run:  |
              sudo apt-get -y -qq update
              sudo apt-get -y -qq install \
                   kvmtool cloud-utils genisoimage qemu-kvm qemu-utils \
                   moreutils mtools
              python -m pip install pexpect
              sudo kvm-ok || echo "kvm-ok failed"
      - name: Check out Mininet
        run:  git clone https://github.com/mininet/mininet
      - name: Build Ubuntu ${{ matrix.flavor }} VM
        run:  python mininet/util/vm/build.py -v -z --nokvm ${{ matrix.flavor }}
      - name: Upload Mininet VM
        uses: actions/upload-artifact@v2
        with:
            name: mininet-vm-${{ matrix.flavor }}
            path: mn-*/*.zip
